server:
  port: 8080

spring:
  application:
    name: seal-sharding
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

sharding.jdbc:
  datasource:
    names: ds0,ds1
    ds0:
      type: com.alibaba.druid.pool.DruidDataSource
      # driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      # url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/seal_sharding?useUnicode=true&characterEncoding=UTF8&useSSL=false
      url: jdbc:p6spy:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/seal_sharding?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: root
      
      # druid
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      validationQuery: select 1
    ds1:
      type: com.alibaba.druid.pool.DruidDataSource
      # driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      # url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/seal_sharding1?useUnicode=true&characterEncoding=UTF8&useSSL=false
      url: jdbc:p6spy:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/seal_sharding1?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: root

      # druid
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      validationQuery: select 1
  config:
    sharding:
      # 读写分离配置
      # master-slave-rules:
      #   ds_0:
      #     masterDataSourceName: ds0
      #     slaveDataSourceNames: ds0_slave_0,ds0_slave_1
      #   ds_1:
      #     masterDataSourceName: ds1
      #     slaveDataSourceNames: ds1_slave_0, ds1_slave_1
      default-database-strategy:
        inline:
          sharding-column: tenant_id
          algorithm-expression: ds$->{tenant_id % 2}
      default-data-source-name: ds0
      # default-table-strategy:
      #   none:
      # default-key-generator-class-name: io.shardingsphere.core.keygen.DefaultKeyGenerator
      tables:
        t_user:
          actual-data-nodes: ds$->{0..1}.t_user_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_user_$->{id.hashCode() % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
      props:
        sql.show: true

---
#============================================
# mybatis 配置
#============================================
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.seal.sharding.entity
  global-config:
    #驼峰下划线转换
    db-column-underline: true
    sql-parser-cache: true
    #刷新mapper 调试神器
    refresh: true
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      db-type:  MYSQL
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_null
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      #驼峰下划线转换
      #column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 配置swagger
swagger:
  enabled: true
  base-package: com.seal.sharding
  title: seal-sharding
  version: 1.0.0.SNAPSHOT
  description: 管理后端服务
  contact:
    name: admin
  global-operation-parameters:
    - name: !!str Authorization
      description: 令牌
      model-ref: string
      parameter-type: header
      required: false
